# Generated by Django 5.0 on 2024-01-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identyfikator', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('is_registred', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.activeevent')),
            ],
            options={
                'verbose_name_plural': 'Bal',
                'unique_together': {('identyfikator', 'login', 'event')},
            },
        ),
    ]
