# Generated by Django 5.0 on 2024-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bal', '0002_alter_bal_identyfikator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bal',
            name='identyfikator',
            field=models.IntegerField(unique=True),
        ),
    ]
