# Generated by Django 5.0 on 2024-01-18 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bal', '0004_bal_data_modyfikacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='bal',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
