# Generated by Django 5.0 on 2024-01-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oddzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_eventu', models.CharField(choices=[('bal', 'Bal'), ('piknik', 'Piknik')], max_length=255)),
                ('rok', models.IntegerField()),
                ('aktywny', models.BooleanField(default=False)),
                ('oddzial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.oddzial')),
            ],
        ),
    ]
