# Generated by Django 5.0 on 2024-01-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_activeevent_options_alter_oddzial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przystanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('oddzial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.oddzial')),
            ],
            options={
                'verbose_name_plural': 'Przystanek',
            },
        ),
        migrations.CreateModel(
            name='Piknik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identyfikator', models.IntegerField()),
                ('login', models.CharField(max_length=255)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('osoba_towarzyszaca', models.BooleanField()),
                ('liczba_dzieci', models.IntegerField(choices=[(0, 'Brak'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('transport_wlasny', models.BooleanField(default=False)),
                ('is_registred', models.BooleanField(default=False)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.activeevent')),
                ('przystanek', models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, to='piknik.przystanek')),
            ],
            options={
                'verbose_name_plural': 'Piknik',
            },
        ),
    ]
