# Generated by Django 4.2.14 on 2024-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piknik', '0003_alter_piknik_transport_wlasny'),
    ]

    operations = [
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='wiek_dziecka_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piknik',
            name='zaakceptowane_regulamin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='piknik',
            name='liczba_dzieci',
            field=models.IntegerField(choices=[(0, 'Brak'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
